name: 医院联系每日定时任务 

# 定时触发：每天早上8点（UTC时间，北京时间16点）运行，支持手动触发
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  daily-hospital-contact:
    runs-on: ubuntu-latest
    timeout-minutes: 65  # 65分钟超时（1小时+5分钟缓冲）
    
    steps:
    - name: 检出代码 
      uses: actions/checkout@v4  # 升级到最新版本v4
      
    - name: 设置Python环境 
      uses: actions/setup-python@v5  # 升级到最新版本v5
      with: 
        python-version: '3.9'
        
    - name: 安装依赖包 
      run: |
        python -m pip install --upgrade pip
        pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple  # 国内镜像加速
        pip install -r requirements.txt 
        
    - name: 下载之前的进度 
      uses: actions/download-artifact@v4  # 关键修复：v3升级到v4
      continue-on-error: true
      with:
        name: progress-data
        path: ./
        
    - name: 运行医院联系程序（限时1小时）
      run: |
        echo "开始运行医院联系程序..." 
        timeout 3600s python github_daily_run.py || echo "程序运行1小时结束"
        
    - name: 保存进度数据 
      uses: actions/upload-artifact@v4  # 关键修复：v3升级到v4
      with:
        name: progress-data
        path: |
          progress.json
          daily_log.txt 
        retention-days: 30
        
    - name: 上传运行日志 
      uses: actions/upload-artifact@v4  # 关键修复：v3升级到v4
      with:
        name: 运行日志-${{ github.run_number }}
        path: 每日日志.txt
        retention-days: 7
